# Generated by Django 4.2.17 on 2024-12-05 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_url_original_url_remove_url_short_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='created_at',
            new_name='generation_time',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='full_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='url',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 19, 57, 51, 92079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='url',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='tiny_url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
